# =====================================
# 2. External DNS
# =====================================
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"  # Ensures this app is deployed before any apps depending on External DNS
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://kubernetes-sigs.github.io/external-dns/
    chart: external-dns
    targetRevision: 1.14.0
    helm:
      values: |
        provider: aws
        region: us-west-2
        policy: sync
        domainFilters:
          - saharbittman.com
        serviceAccount:
          create: true
          name: external-dns
          annotations:
            eks.amazonaws.com/role-arn: arn:aws:iam::634647866665:role/eks-external-dns-role-49kgdpkf
        txtOwnerId: eksdemo-cluster
        sources:
          - ingress
          - service
        cleanupOnDelete: true  # ensures DNS records are deleted when the ingress is deleted
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true # Allows the application to be empty without causing a failure
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true  # Ensures resources are created before any are deleted
      - PrunePropagationPolicy=foreground # Ensures resources are deleted in the correct order
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m