# =====================================
# 3. Flask App
# =====================================
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flask-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/sahar449/aws-eks-tf-argocd.git
    targetRevision: HEAD
    path: chart-flask
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false  # Changed to false - safer
    syncOptions:
      - PruneLast=true
      - PrunePropagationPolicy=foreground
      - CreateNamespace=false  # namespace already exists
      - ApplyOutOfSyncOnly=true  # More efficient
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m  # Fixed typo (was 3mrs)